import type { Metadata } from "next";
import type { RowDataPacket } from "mysql2";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getDb } from "../../../lib/db";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
export const dynamic="force-dynamic";
interface Project extends RowDataPacket{name:string;website_url:string;tagline:string;summary:string;challenge:string;solution:string;impact:string;technologies:string;accent_color:string;status:string;launched_at:Date|null}
async function getProject(slug:string){const [rows]=await getDb().execute<Project[]>("SELECT name,website_url,tagline,summary,challenge,solution,impact,technologies,accent_color,status,launched_at FROM projects WHERE slug=? AND featured=TRUE LIMIT 1",[slug]);return rows[0]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const p=await getProject((await params).slug);return p?{title:`${p.name} — FlightCoders project`,description:p.summary}:{title:"Project not found"}}
export default async function ProjectDetail({params}:{params:Promise<{slug:string}>}){const p=await getProject((await params).slug);if(!p)notFound();return <main><SiteHeader/><article className="project-case shell" style={{"--project-accent":p.accent_color} as React.CSSProperties}><header><span>// PROJECT CASE STUDY / {p.status.toUpperCase()}</span><div className="project-case-title"><h1>{p.name}</h1><div className="case-mark">{p.name.slice(0,1)}</div></div><h2>{p.tagline}</h2><p>{p.summary}</p><div className="case-actions"><a className="button" href={p.website_url} target="_blank" rel="noreferrer">Visit live product ↗</a><Link href="/projects">All projects</Link></div></header><section className="case-facts"><div><span>LAUNCHED</span><b>{p.launched_at?new Date(p.launched_at).toLocaleDateString("en",{month:"long",year:"numeric"}):"Live"}</b></div><div><span>STATUS</span><b>{p.status}</b></div><div><span>BUILT BY</span><b>FlightCoders</b></div></section><section className="case-narrative"><div><span>01 / THE CHALLENGE</span><h2>What needed to change.</h2><p>{p.challenge}</p></div><div><span>02 / THE SYSTEM</span><h2>How we built the answer.</h2><p>{p.solution}</p></div><div><span>03 / THE IMPACT</span><h2>What the product unlocks.</h2><p>{p.impact}</p></div></section><section className="case-stack"><span>04 / TECHNOLOGY</span><h2>Engineered for a reliable flight path.</h2><div>{p.technologies.split(",").map((item,index)=><b key={item}><small>{String(index+1).padStart(2,"0")}</small>{item.trim()}</b>)}</div></section></article><SiteFooter/></main>}
