"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
type Post={id:number;name:string;role:string|null;kind:string;content:string;project_url:string|null;created_at:string};
const labels:Record<string,string>={project:"Project showcase",question:"Questions",collaboration:"Find collaborators"};
export function CommunityFeed({signedIn=false}:{signedIn?:boolean}){
 const [posts,setPosts]=useState<Post[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/community");const data=await response.json();if(!response.ok)throw Error(data.error);setPosts(data.posts);}catch(error){setError(error instanceof Error?error.message:"Could not load the feed.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const controller=new AbortController();fetch("/api/community",{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);return data;}).then(data=>setPosts(data.posts)).catch(error=>{if(!controller.signal.aborted)setError(error instanceof Error?error.message:"Could not load the feed.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return ()=>controller.abort();},[]);
 async function publish(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setSaving(true);setNotice("");try{const response=await fetch("/api/community",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fields))});const data=await response.json();if(!response.ok)throw Error(data.error);form.reset();setNotice("Published. Your post is now visible to the community.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Could not publish.");}finally{setSaving(false);}}
 const visible=posts.filter(post=>(filter==="all"||post.kind===filter)&&`${post.name} ${post.content}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="network-feed" aria-label="Community feed">
 {signedIn?<form className="network-compose" onSubmit={publish}><div className="network-section-title"><h2>What are you building?</h2><span>SHARE IN PUBLIC</span></div><label htmlFor="post-content">Share an update, ask a question, or invite collaborators</label><textarea id="post-content" name="content" required maxLength={2000} rows={3} placeholder="A small idea could be the start of something great…"/><div className="network-compose-fields"><label>Post type<select name="kind"><option value="project">Project showcase</option><option value="question">Question</option><option value="collaboration">Looking for collaborators</option></select></label><label>Project link (optional)<input name="project_url" type="url" maxLength={500} placeholder="https://github.com/you/project"/></label></div><footer><small>Public posts · Be kind, specific, and constructive.</small><button disabled={saving}>{saving?"Publishing…":"Publish update ↗"}</button></footer><p role="status">{notice}</p></form>:<div className="network-invite"><div><h2>Your next collaborator could be here.</h2><p>Share your work and build alongside people around the world.</p></div><Link href="/login?next=/dashboard">Sign in to contribute ↗</Link></div>}
 <div className="network-section-title"><h2>Community dispatch</h2><button className="network-text-button" onClick={load} disabled={loading}>Refresh ↻</button></div><label className="network-search">Search recent posts<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search builders, ideas, or technologies…"/></label><div className="network-tabs" aria-label="Filter posts">{Object.entries({all:"All posts",...labels}).map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
 {loading?<div className="network-empty" role="status">Loading community updates…</div>:error?<div className="network-empty" role="alert"><h3>We couldn’t load the conversation.</h3><p>{error}</p><button onClick={load}>Try again</button></div>:visible.length?visible.map(post=><article className="network-post" key={post.id}><header><span className="network-avatar">{post.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</span><div><h3>{post.name}</h3><small>{post.role||"Community builder"}</small></div><span className="network-post-kind">{labels[post.kind]}</span></header><p>{post.content}</p>{post.project_url&&<a href={post.project_url} target="_blank" rel="noopener noreferrer nofollow ugc">Explore project ↗</a>}<footer><time dateTime={post.created_at}>{new Date(post.created_at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</time><span>BUILDING IN PUBLIC</span></footer></article>):<div className="network-empty"><span>✳</span><h3>{search||filter!=="all"?"No matching updates yet.":"Every community starts with a conversation."}</h3><p>{search||filter!=="all"?"Try another search or explore all posts.":"Share your first project, introduce an idea, or ask for a fresh perspective."}</p></div>}
 </section>;
}
