"use client";
import {useMemo,useState} from "react";
import {flightChallenges} from "../../lib/flightChallenges";

type TestResult={name:string;passed:boolean;message:string;duration:number};
function execute(code:string,tests:{name:string;code:string}[]):Promise<TestResult[]>{
 return new Promise((resolve)=>{
  const source=`self.onmessage=async(e)=>{const {code,tests}=e.data;const out=[];try{(0,eval)(code);for(const t of tests){const s=Date.now();try{const fn=new Function(t.code);await fn();out.push({name:t.name,passed:true,message:'Nominal',duration:Date.now()-s})}catch(x){out.push({name:t.name,passed:false,message:String(x&&x.message||x),duration:Date.now()-s})}}self.postMessage({out})}catch(x){self.postMessage({error:String(x&&x.message||x)})}}`;
  const worker=new Worker(URL.createObjectURL(new Blob([source],{type:"text/javascript"}))); const timer=setTimeout(()=>{worker.terminate();resolve(tests.map(t=>({name:t.name,passed:false,message:"Execution exceeded 2000ms",duration:2000})))},2000);
  worker.onmessage=(event)=>{clearTimeout(timer);worker.terminate();resolve(event.data.out||tests.map(t=>({name:t.name,passed:false,message:event.data.error||"Runtime fault",duration:0})))};
  worker.postMessage({code,tests});
 });
}
export function FlightIDE({initialSolved}:{initialSolved:string[]}){
 const [index,setIndex]=useState(0), challenge=flightChallenges[index];
 const [code,setCode]=useState(challenge.starter),[results,setResults]=useState<TestResult[]>([]),[running,setRunning]=useState(false),[consoleText,setConsoleText]=useState("Awaiting flight program…"),[solved,setSolved]=useState(new Set(initialSolved)),[filter,setFilter]=useState("");
 const [history,setHistory]=useState<Array<{challenge_slug:string;passed:number;tests_passed:number;total_tests:number;runtime_ms:number;created_at:string}>>([]),[historyOpen,setHistoryOpen]=useState(false),[draftNotice,setDraftNotice]=useState("");
 const lines=useMemo(()=>code.split("\n").length,[code]);
 const visibleChallenges=flightChallenges.filter(item=>(item.title+item.system+item.difficulty).toLowerCase().includes(filter.toLowerCase()));
 function selectMission(i:number){setIndex(i);const saved=localStorage.getItem(`fc_draft_${flightChallenges[i].slug}`);setCode(saved||flightChallenges[i].starter);setResults([]);setDraftNotice(saved?"Recovered saved draft":"");setConsoleText("Mission loaded. Complete the flight program, then run validation.")}
 function saveDraft(){localStorage.setItem(`fc_draft_${challenge.slug}`,code);setDraftNotice("Draft secured on this device");}
 async function openHistory(){const response=await fetch("/api/lab/submissions");const data=await response.json();setHistory(data.submissions||[]);setHistoryOpen(true)}
 async function run(submit=false){setRunning(true);setConsoleText("Compiling isolated flight program…");const r=await execute(code,challenge.tests);setResults(r);const passed=r.every(x=>x.passed);setConsoleText(passed?"ALL SYSTEMS NOMINAL — every validation gate passed.":"VALIDATION ABORTED — inspect failed systems below.");setRunning(false);if(submit){await fetch("/api/lab/submissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({challengeSlug:challenge.slug,language:"javascript",code,passed,testsPassed:r.filter(x=>x.passed).length,totalTests:r.length,runtimeMs:r.reduce((n,x)=>n+x.duration,0)})});if(passed)setSolved(s=>new Set([...s,challenge.slug]));}}
 return <div className="flight-ide">
  <aside className="mission-rail"><div className="rail-heading"><span>MISSION BANK</span><b>{solved.size}/{flightChallenges.length}</b></div><label className="mission-search"><span>⌕</span><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter systems" aria-label="Filter coding missions"/></label>{visibleChallenges.map(item=>{const i=flightChallenges.indexOf(item);return <button key={item.slug} className={i===index?"active":""} onClick={()=>selectMission(i)}><i>{solved.has(item.slug)?"✓":String(i+1).padStart(2,"0")}</i><span><b>{item.title}</b><small>{item.system}</small></span><em>{item.difficulty}</em></button>})}<button className="history-trigger" onClick={openHistory}><i>↺</i><span><b>Submission telemetry</b><small>Review recent attempts</small></span></button><div className="rail-signal"><i/><span>JUDGE ONLINE</span><small>Browser-isolated · 2s limit</small></div></aside>
  <section className="mission-brief"><header><span>MISSION {String(index+1).padStart(2,"0")} / {challenge.system}</span><b>{challenge.difficulty} · {challenge.xp} XP</b></header><h1>{challenge.title}</h1><p>{challenge.brief}</p><h2>Flight contract</h2><code>{challenge.contract}</code><h2>Operational constraints</h2><ul>{challenge.constraints.map(x=><li key={x}>{x}</li>)}</ul><div className="architecture-map" aria-label="System architecture"><span>SENSORS</span><i>→</i><span>FLIGHT CORE</span><i>→</i><span>ACTUATORS</span><b>REDUNDANCY BUS / LIVE</b></div></section>
  <section className="ide-panel"><header><div><i/><i/><i/><span>flight_solution.js {draftNotice&&<b>· {draftNotice}</b>}</span></div><nav><button className="active">JavaScript</button><button disabled title="Coming soon">Python</button><button disabled title="Coming soon">C++</button></nav><div className="ide-actions"><button onClick={saveDraft}>Save</button><button onClick={()=>{setCode(challenge.starter);setResults([]);localStorage.removeItem(`fc_draft_${challenge.slug}`)}}>Reset</button><button onClick={()=>run(false)} disabled={running}>▶ Run</button><button className="submit-code" onClick={()=>run(true)} disabled={running}>{running?"Validating…":"Submit flight plan"}</button></div></header><div className="editor-shell"><pre aria-hidden>{Array.from({length:lines},(_,i)=><span key={i}>{i+1}</span>)}</pre><textarea spellCheck={false} aria-label="Flight code editor" value={code} onChange={e=>{setCode(e.target.value);setDraftNotice("")}} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter"){e.preventDefault();run(false)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveDraft()}}}/></div><div className="judge-console"><header><span>VALIDATION CONSOLE · CTRL/⌘ + ENTER TO RUN</span><b>{results.filter(x=>x.passed).length}/{results.length||challenge.tests.length} GATES</b></header><p>{consoleText}</p>{results.map(r=><div key={r.name} className={r.passed?"pass":"fail"}><b>{r.passed?"PASS":"FAIL"}</b><span>{r.name}</span><small>{r.message} · {r.duration}ms</small></div>)}</div></section>
  {historyOpen&&<div className="history-layer" role="dialog" aria-modal="true" aria-label="Submission telemetry"><section><header><div><span>FLIGHT RECORDER</span><h2>Submission telemetry</h2></div><button onClick={()=>setHistoryOpen(false)} aria-label="Close submission history">×</button></header><div className="history-list">{history.map((item,i)=><article key={`${item.created_at}-${i}`}><b className={item.passed?"passed":"failed"}>{item.passed?"PASSED":"FAILED"}</b><span><strong>{flightChallenges.find(x=>x.slug===item.challenge_slug)?.title||item.challenge_slug}</strong><small>{new Date(item.created_at).toLocaleString()}</small></span><em>{item.tests_passed}/{item.total_tests} gates · {item.runtime_ms}ms</em></article>)}{!history.length&&<p>No flight programs submitted yet.</p>}</div></section></div>}
 </div>
}
