"use client";
import { useState } from "react";
import type { SocialLinks } from "../../lib/profile";
export function ProfileForm({user,links}:{user:{name:string;email:string;role:string|null;goal:string|null};links:SocialLinks}) {
 const [name,setName]=useState(user.name),[role,setRole]=useState(user.role||""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();setSaving(true);setNotice("");
  const body=Object.fromEntries(new FormData(event.currentTarget).entries());
  try{const response=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setNotice(response.ok?"Your profile has been saved.":result.error||"Could not save. Please try again.");}
  catch{setNotice("Connection interrupted. Please try again.");}finally{setSaving(false);}
 }
 return <div className="profile-editor"><aside className="profile-preview"><span className="profile-monogram">{name.trim().split(/\s+/).map(p=>p[0]).join("").slice(0,2).toUpperCase()||"FC"}</span><span className="fc-section-label">FLIGHTCODERS / BUILDER</span><h2>{name||"Your name"}</h2><p>{role||"Your next chapter starts here."}</p><small>Your personal profile. Your email stays private.</small></aside><form className="simple-profile-form" onSubmit={submit}><fieldset><legend>01 / About you</legend><label>Full name<input name="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={80} autoComplete="name"/></label><label>Email<input value={user.email} readOnly disabled/></label><label>What do you do?<input name="role" value={role} onChange={e=>setRole(e.target.value)} maxLength={80} placeholder="Developer, designer, curious builder…"/></label><label>Short bio<textarea name="goal" defaultValue={user.goal||""} maxLength={1000} rows={4} placeholder="What are you building?"/></label></fieldset><fieldset><legend>02 / Find you online</legend><p>All links are optional. Use complete https:// links.</p>{([["github","GitHub","https://github.com/username"],["linkedin","LinkedIn","https://linkedin.com/in/username"],["website","Personal website","https://yourwebsite.com"],["x","X / Twitter","https://x.com/username"]] as const).map(([key,title,placeholder])=><label key={key}>{title}<input type="url" name={key} defaultValue={links[key]} maxLength={500} placeholder={placeholder}/></label>)}</fieldset><div className="profile-save"><button className="hf-primary" disabled={saving}>{saving?"Saving…":"Save profile ↗"}</button><p role="status" aria-live="polite">{notice}</p></div></form></div>;
}
