import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { featuredProjects } from "../../lib/featured-projects";
import "./projects.css";
export const metadata:Metadata={title:"Projects built by FlightCoders",description:"Explore original FlightCoders projects, including Daemon and Veyra Editor."};
export default function ProjectsPage(){return <main className="hf-site"><SiteHeader/><section className="fc-projects-page shell"><header className="fc-projects-intro"><span className="fc-section-label">FLIGHTCODERS / BUILT IN THE OPEN</span><h1>Not just ideas.<br/><em>Things we built.</em></h1><p>A home for our major projects. Explore the products, inspect the code, and see what happens when curiosity becomes software.</p><div className="fc-projects-count"><span>{String(featuredProjects.length).padStart(2,"0")} / PROJECT COLLECTION</span><a href="https://github.com/fcopensource" target="_blank" rel="noopener noreferrer">Explore our GitHub ↗</a></div></header>{featuredProjects.map((project,index)=><article className="fc-original-project" key={project.slug}><div className="fc-original-heading"><span>PROJECT {String(index+1).padStart(2,"0")}</span><span>OPEN SOURCE / {project.category}</span></div><div className="fc-original-grid"><div className="fc-original-copy"><span className="fc-project-monogram" aria-hidden="true">{project.name.slice(0,1)}_</span><h2>{project.name}</h2><h3>{project.tagline}</h3><p>{project.description}</p><div className="fc-project-stack">{project.stack.map(tag=><span key={tag}>{tag}</span>)}</div><div className="fc-project-actions"><a className="hf-primary" href={project.repository} target="_blank" rel="noopener noreferrer">View source on GitHub ↗</a><a href={project.repository+"#-quick-start"} target="_blank" rel="noopener noreferrer">Build & run ↗</a></div></div><figure className="fc-project-screen"><div><span>{project.name.toUpperCase()} / NATIVE DESKTOP</span><span>● ● ●</span></div><Image src={project.image} alt={project.imageAlt} width={1600} height={1000} sizes="(max-width: 850px) 90vw, 60vw" priority={index === 0}/><figcaption>Actual project screenshot · Source: FlightCoders / {project.name}</figcaption></figure></div><div className="fc-project-features">{project.features.map(([title,description],i)=><section key={title}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></section>)}</div><footer><span>{project.platform}</span><span>{project.license} · {project.runtime}</span></footer></article>)}<section className="fc-project-next"><span className="fc-section-label">THE COLLECTION CONTINUES</span><h2>More experiments.<br/>More things worth building.</h2><p>New FlightCoders projects will be added here as they take shape.</p><Link href="/community">Meet the community ↗</Link></section></section><SiteFooter/></main>;}
