import type { Metadata } from "next";
import type { RowDataPacket } from "mysql2";
import Link from "next/link";
import { getDb } from "../../lib/db";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Products and projects",description:"Explore products designed and developed by FlightCoders, including TweetQueue and CareerFit."};
interface Project extends RowDataPacket{id:number;slug:string;name:string;website_url:string;tagline:string;summary:string;technologies:string;accent_color:string;status:string;launched_at:Date|null}
export default async function ProjectsPage(){const [projects]=await getDb().execute<Project[]>("SELECT id,slug,name,website_url,tagline,summary,technologies,accent_color,status,launched_at FROM projects WHERE featured=TRUE ORDER BY launched_at DESC,id DESC");return <main><SiteHeader/><section className="content-hero project-hero shell"><span>// FLIGHTCODERS LABS / SHIPPED SYSTEMS</span><h1>Products built<br/><em>to move people.</em></h1><p>Explore digital products conceived, designed, and engineered by FlightCoders—from creator infrastructure to AI-powered career intelligence.</p></section><section className="projects-showcase shell">{projects.map((project,index)=><article className="project-showcase-card" key={project.id} style={{"--project-accent":project.accent_color} as React.CSSProperties}><div className="project-index"><span>{String(index+1).padStart(2,"0")}</span><b>{project.status}</b></div><div className="project-orbit" aria-hidden="true"><i/><i/><strong>{project.name.slice(0,1)}</strong></div><div className="project-copy"><small>FLIGHTCODERS ORIGINAL / {project.launched_at?new Date(project.launched_at).getFullYear():"LIVE"}</small><h2>{project.name}</h2><h3>{project.tagline}</h3><p>{project.summary}</p><div className="project-tech">{project.technologies.split(",").map(item=><span key={item}>{item.trim()}</span>)}</div><footer><Link href={`/projects/${project.slug}`}>Read the case study ↗</Link><a href={project.website_url} target="_blank" rel="noreferrer">Visit {project.name} ↗</a></footer></div></article>)}</section><SiteFooter/></main>}
