import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { GitHubAuthButton } from "../components/GitHubAuthButton";

export default async function RegisterPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const params=await searchParams;
 return <main className="hf-auth-page"><SiteHeader/><section className="auth-shell shell"><div className="auth-aside hf-auth-aside"><div className="section-kicker dark">// JOIN THE NETWORK</div><h1>Your next<br/><em>breakthrough starts here.</em></h1><p>Create a builder profile, meet exceptional collaborators, enter global hackathons, and put your best work in front of the world.</p><div className="hf-member-proof"><span><b>Build</b> real projects</span><span><b>Meet</b> your collaborators</span><span><b>Grow</b> your skills</span></div></div><form className="auth-card register-card" action="/api/auth/register" method="post"><span className="auth-code">JOIN / FC-26</span><h2>Create your builder profile</h2><p>One account for your hackathons, collaborators, projects, and progress.</p>{params.error&&<div className="form-error" role="alert">{params.error}</div>}<GitHubAuthButton label="Create profile with GitHub"/><div className="auth-divider"><span/>OR REGISTER WITH EMAIL<span/></div><div className="register-fields"><label>Full name<input name="name" autoComplete="name" placeholder="Your name" required maxLength={80}/></label><label>Email address<input type="email" name="email" autoComplete="email" placeholder="builder@example.com" required maxLength={190}/></label><label>Password<input type="password" name="password" autoComplete="new-password" placeholder="8+ characters" required minLength={8} maxLength={72}/></label><label>Confirm password<input type="password" name="confirmPassword" autoComplete="new-password" placeholder="Repeat password" required minLength={8} maxLength={72}/></label><label>Current role<select name="role" defaultValue=""><option value="">Choose a role</option><option>Student</option><option>Software engineer</option><option>Product designer</option><option>Data scientist</option><option>Founder</option><option>Other</option></select></label><label>Frontier interest<select name="track" defaultValue=""><option value="">Choose a technology</option><option>AI Agents</option><option>Spatial Computing</option><option>Web3 &amp; ZK</option><option>Edge AI</option><option>Developer Tools</option></select></label></div><small className="password-rule">Use uppercase, lowercase, a number, and at least 8 characters.</small><label className="terms-check"><input type="checkbox" name="terms" required/><span>I agree to the <Link href="/terms">Terms</Link> and <Link href="/privacy">Privacy Policy</Link>.</span></label><button className="auth-button auth-submit" type="submit"><span className="auth-brand-mark">FC</span> Create my profile <b>↗</b></button><p className="auth-switch">Already a member? <Link href="/login">Log in</Link></p></form></section><SiteFooter/></main>;
}
