import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { GitHubAuthButton } from "../components/GitHubAuthButton";

export default async function RegisterPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const params = await searchParams;
  return <main><SiteHeader/><section className="auth-shell shell"><div className="auth-aside"><div className="section-kicker dark">// START YOUR MISSION</div><h1>Your code.<br/><em>New altitude.</em></h1><p>Create your private FlightCoders account, choose a first track, and enter a global crew serious about flight technology.</p><div className="cohort-meter"><div><b>COHORT 04</b><span>84% reserved</span></div><i><span/></i><small>Applications close August 24</small></div></div><form className="auth-card register-card" action="/api/auth/register" method="post"><span className="auth-code">JOIN / FC-04</span><h2>Create your account</h2><p>One account. Your projects, progress, crew, and AI mentor.</p>{params.error && <div className="form-error" role="alert">{params.error}</div>}<GitHubAuthButton label="Create account with GitHub"/><div className="auth-divider"><span/>OR REGISTER WITH EMAIL<span/></div><div className="register-fields"><label>Full name<input name="name" autoComplete="name" placeholder="Your name" required maxLength={80}/></label><label>Email address<input type="email" name="email" autoComplete="email" placeholder="pilot@example.com" required maxLength={190}/></label><label>Password<input type="password" name="password" autoComplete="new-password" placeholder="8+ characters" required minLength={8} maxLength={72}/></label><label>Confirm password<input type="password" name="confirmPassword" autoComplete="new-password" placeholder="Repeat password" required minLength={8} maxLength={72}/></label><label>Current role<select name="role" defaultValue=""><option value="">Choose a role</option><option>Student</option><option>Software engineer</option><option>Aerospace engineer</option><option>Data scientist</option><option>Founder</option><option>Other</option></select></label><label>First flight path<select name="track" defaultValue=""><option value="">Choose a track</option><option>Flight Systems</option><option>Drone Autonomy</option><option>Aviation Data</option><option>Safety Engineering</option></select></label></div><small className="password-rule">Use uppercase, lowercase, a number, and at least 8 characters.</small><label className="terms-check"><input type="checkbox" name="terms" required/><span>I agree to the <Link href="/terms">Terms</Link> and <Link href="/privacy">Privacy Policy</Link>.</span></label><button className="auth-button auth-submit" type="submit"><span className="auth-brand-mark">F/C</span> Create my account <b>↗</b></button><p className="auth-switch">Already a member? <Link href="/login">Log in</Link></p></form></section><SiteFooter/></main>;
}
