import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; next?: string; verified?: string }> }) {
  const params = await searchParams;
  const next = params.next?.startsWith("/") && !params.next.startsWith("//") ? params.next : "/dashboard";
  return <main><SiteHeader/><section className="auth-shell shell"><div className="auth-aside"><div className="section-kicker dark">// MEMBER ACCESS</div><h1>Welcome<br/><em>back, pilot.</em></h1><p>Return to your dashboard, continue your current track, and see what your crew shipped while you were away.</p><div className="flight-login-visual" aria-hidden="true"><span className="login-route"/><span className="login-plane">✈</span><code>session.authenticate()<br/>clearance: GRANTED</code></div></div><form className="auth-card" action="/api/auth/login" method="post"><span className="auth-code">AUTH / FC-01</span><h2>Log in to FlightCoders</h2><p>Use your private FlightCoders account to continue.</p>{params.verified && <div className="form-success" role="status">Email verified. Your flight deck is ready.</div>}{params.error && <div className="form-error" role="alert">{params.error}</div>}<input type="hidden" name="next" value={next}/><label>Email address<input type="email" name="email" autoComplete="email" placeholder="pilot@example.com" required/></label><label>Password<input type="password" name="password" autoComplete="current-password" placeholder="Enter your password" required/></label><button className="auth-button auth-submit" type="submit"><span className="auth-brand-mark">F/C</span> Log in securely <b>↗</b></button><p className="verification-link"><Link href="/verify-email">Resend email verification</Link></p><div className="auth-divider"><span/>FLIGHTCODERS SECURE ACCESS<span/></div><ul><li>✓ Verified member identity</li><li>✓ Secure HTTP-only session</li><li>✓ 30-day automatic expiry</li></ul><small className="auth-legal">By logging in, you agree to our <Link href="/terms">Terms</Link> and acknowledge our <Link href="/privacy">Privacy Policy</Link>.</small><p className="auth-switch">New to FlightCoders? <Link href="/register">Create an account</Link></p></form></section><SiteFooter/></main>;
}
