import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { GitHubAuthButton } from "../components/GitHubAuthButton";

export default async function LoginPage({searchParams}:{searchParams:Promise<{error?:string;next?:string;verified?:string}>}){
 const params=await searchParams;
 const next=params.next?.startsWith("/")&&!params.next.startsWith("//")?params.next:"/profile";
 return <main className="hf-auth-page"><SiteHeader/><section className="auth-shell shell"><div className="auth-aside hf-auth-aside"><div className="section-kicker dark">// MEMBER TERMINAL</div><h1>Welcome<br/><em>back, builder.</em></h1><p>Return to your network, discover your next challenge, and keep shipping work that moves technology forward.</p><div className="hf-auth-signal" aria-hidden="true"><div><i/><i/><i/></div><code>network.connect()<br/><span>identity: verified</span><br/>status: ready_</code><b>FC<br/>26</b></div></div><form className="auth-card" action="/api/auth/login" method="post"><span className="auth-code">AUTH / FC-01</span><h2>Log in to FlightCoders</h2><p>Your projects, teams, challenges, and builder profile are waiting.</p>{params.verified&&<div className="form-success" role="status"><strong>✓ Email verified successfully</strong><span>Your FlightCoders account is active. You can now log in.</span></div>}{params.error&&<div className="form-error" role="alert">{params.error}</div>}<GitHubAuthButton next={next}/><div className="auth-divider"><span/>OR USE EMAIL<span/></div><input type="hidden" name="next" value={next}/><label>Email address<input type="email" name="email" autoComplete="email" placeholder="builder@example.com" required/></label><label>Password<input type="password" name="password" autoComplete="current-password" placeholder="Enter your password" required/></label><button className="auth-button auth-submit" type="submit"><span className="auth-brand-mark">FC</span> Enter the network <b>↗</b></button><p className="verification-link"><Link href="/verify-email">Resend email verification</Link></p><div className="auth-divider"><span/>SECURE BUILDER ACCESS<span/></div><ul><li>✓ Verified builder identity</li><li>✓ Secure HTTP-only session</li><li>✓ Private project workspace</li></ul><small className="auth-legal">By logging in, you agree to our <Link href="/terms">Terms</Link> and acknowledge our <Link href="/privacy">Privacy Policy</Link>.</small><p className="auth-switch">New to FlightCoders? <Link href="/register">Create a profile</Link></p></form></section><SiteFooter/></main>;
}
