import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";

const paths = [
  { code:"FS-101", title:"Flight Systems", level:"Intermediate", duration:"12 weeks", projects:"4 projects", desc:"Build the software layer behind navigation, sensor fusion, telemetry, and resilient airborne systems.", skills:["Python","C++","MAVLink","Kalman filters"], project:"Capstone: autonomous route controller" },
  { code:"DA-204", title:"Drone Autonomy", level:"Advanced", duration:"10 weeks", projects:"3 projects", desc:"Give machines spatial awareness. Progress from control theory to a vision-guided autonomous drone.", skills:["ROS 2","OpenCV","PX4","Control loops"], project:"Capstone: vision-guided landing" },
  { code:"FD-100", title:"Aviation Data", level:"Beginner", duration:"8 weeks", projects:"5 projects", desc:"Learn software through real ADS-B and weather data, then ship tools pilots and operators can use.", skills:["Python","SQL","APIs","Data viz"], project:"Capstone: live flight intelligence desk" },
  { code:"SE-310", title:"Safety Engineering", level:"Advanced", duration:"6 weeks", projects:"2 projects", desc:"Design software that fails predictably, recovers gracefully, and earns trust in safety-critical environments.", skills:["Rust","Testing","FMEA","Observability"], project:"Capstone: fault-tolerant control service" },
];

export default function TracksPage(){return <main><SiteHeader/><section className="subhero shell"><div className="section-kicker dark">// LEARNING PATHS</div><h1>Choose your<br/><em>flight plan.</em></h1><p>Serious, project-led programs for developers who want their work to leave the ground.</p></section><section className="path-grid shell">{paths.map((p,i)=><article className="path-card" key={p.code}><div className="path-top"><span>{p.code}</span><span>0{i+1}</span></div><h2>{p.title}</h2><p>{p.desc}</p><div className="path-facts"><span><small>LEVEL</small>{p.level}</span><span><small>DURATION</small>{p.duration}</span><span><small>OUTPUT</small>{p.projects}</span></div><div className="skill-row">{p.skills.map(s=><b key={s}>{s}</b>)}</div><div className="capstone">✦ {p.project}</div><Link className="path-link" href="/register">View curriculum <span>↗</span></Link></article>)}</section><section className="mini-cta"><div className="shell"><h2>Not sure where to begin?</h2><p>Tell us what you want to build. We’ll map the shortest runway.</p><Link className="button white" href="/register">Get a path recommendation ↗</Link></div></section><SiteFooter/></main>}
