import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { CommunityFeed } from "../components/CommunityFeed";
import "../community/network.css";
export const metadata={title:"Your workspace"};
export default async function DashboardPage(){
 const user=await requireUser("/dashboard");
 return <main className="network-app"><aside className="network-sidebar"><Link className="network-brand" href="/">✳ FlightCoders</Link><span className="network-eyebrow">YOUR BUILDER WORKSPACE</span><nav aria-label="Workspace"><Link href="/dashboard" aria-current="page">◈ Overview</Link><Link href="/community">◎ Community</Link><Link href="/projects">↗ Project gallery</Link><Link href="/flight-lab">⌘ Coding challenges</Link><Link href="/tracks">▤ Learning tracks</Link><Link href="/jobs">◇ Opportunities</Link><Link href="/profile">○ Your profile</Link></nav><div className="network-sidebar-note"><span>BUILD WITHOUT BORDERS</span><p>Different time zones.<br/>Shared ambition.</p></div><form action="/api/auth/logout" method="post"><button>Sign out ↗</button></form></aside><div className="network-workspace"><header className="network-topbar"><span>Workspace <b>/ Overview</b></span><Link href="/profile">{user.name} ↗</Link></header><section className="network-welcome"><span className="network-eyebrow">A LITTLE CURIOSITY. ENDLESS POSSIBILITY.</span><h1>Make something<br/><em>worth sharing, {user.name.split(" ")[0]}.</em></h1><p>Your place to find a fresh perspective, meet collaborators, and turn the next idea into something real.</p><Link href="/profile">Complete your builder profile ↗</Link><div className="network-orbits" aria-hidden="true">✳</div></section><div className="network-quicklinks">{[["01","Meet your community","Ask, share, collaborate","/community"],["02","Find your next challenge","Put an idea into practice","/flight-lab"],["03","Explore what’s shipped","Learn from real projects","/projects"]].map(([n,title,detail,url])=><Link key={n} href={url}><span>{n} / EXPLORE</span><h2>{title} ↗</h2><p>{detail}</p></Link>)}</div><div className="network-columns"><CommunityFeed signedIn/><aside className="network-rail"><article><span className="network-eyebrow">YOUR NEXT STEP</span><h2>Good work deserves to be seen.</h2><p>Add your role, tell your story, and link the projects you’re proud of.</p><Link href="/profile">Edit your profile ↗</Link></article><article><span className="network-eyebrow">COMMUNITY CULTURE</span><h2>Build together.<br/>Grow together.</h2><ul><li>Share what you learn.</li><li>Give constructive feedback.</li><li>Credit your collaborators.</li><li>Welcome every experience level.</li></ul></article><p className="network-footnote">FlightCoders · Made for curious minds everywhere.</p></aside></div></div></main>;
}
